index:
    path: /
    defaults: { _controller: AppBundle:Default:index}

login:
    path: /login
    defaults: { _controller: AppBundle:Security:login}

logout:
    path: /logout
    defaults: { _controller: AppBundle:Security:logout}
    
create:
    path: /create
    defaults: { _controller: AppBundle:Security:create}
    
register:
    path: /registeration
    defaults: { _controller: AppBundle:Security:register}
